language: node_js
node_js:
  - '8'

sudo: false

branches:
  only:
    - master
    - development

install:
  - yarn

script:
  - yarn test

after_success:
  - yarn test --coverage --coverageReporters=text-lcov | npx coveralls

cache:
  yarn: true
  directories:
    - 'node_modules'

notifications:
  slack:
    secure: $SLACK_TOKEN
  pushover:
    api_key: $PO_TOKEN
    users:
      - $PO_KEY

deploy:
  - provider: npm
    email: mouafa.ahmed@smartfrog.com
    api_key:
      secure: $NPM_TOKEN
    on:
      repo: mouafa/roya
      branch: master
    skip_cleanup: true

  - provider: npm
    email: mouafa.ahmed@smartfrog.com
    api_key:
      secure: $NPM_TOKEN
    on:
      repo: mouafa/roya
      branch: development
    skip_cleanup: true
    tag: next
